# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - checkout: self

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathtoPublish: '$(build.artifactStagingDirectory)'
        artifactName: 'drop'

    - script: |
        dir $(build.artifactStagingDirectory)\drop
      displayName: 'List Artifact Staging Directory Contents'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Test Job'
    steps:
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy to ProjecTasksCosmos'
      inputs:
        azureSubscription: 'Azure subscription 1(ae066153-bd3c-4b67-a2c8-2d4d8ea1ce38)'
        appType: 'webApp'
        appName: 'ProjectTaskCosmos20240329132020'
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
        deploymentMethod: 'auto'

    - task: AzureWebApp@1
      displayName: 'Deploy to ProjectTasks'
      inputs:
        azureSubscription: 'Azure subscription 1(ae066153-bd3c-4b67-a2c8-2d4d8ea1ce38)'
        appType: 'webApp'
        appName: 'ProjectTasks20240329135526'
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
        deploymentMethod: 'auto'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(ae066153-bd3c-4b67-a2c8-2d4d8ea1ce38)'
        appType: 'functionApp'
        appName: 'ProjectTasksFunction20240401142019'
        package: '$(System.ArtifactsDirectory)/drop/*.zip'
        deploymentMethod: 'auto'

- stage: Notify
  displayName: 'Notification Stage'
  dependsOn: [Build, Test, Deploy]
  jobs:
  - job: Notify
    displayName: 'Send Email Notification'
    steps:
    - task: SendEmail@1
      inputs:
        To: 'jocami.jm.jm@gmail.com'
        From: 'jovanmiladinovice14@gmail.com'
        Subject: 'Pipeline Status: $(Build.Result)'
        Body: |
          The pipeline $(Build.DefinitionName) has completed with status: $(Build.Result).
          Build number: $(Build.BuildNumber)
          Build reason: $(Build.Reason)
          Build URL: $(Build.BuildUri)
        BodyAsHtml: false
        AddAttachment: false
